### ISSUE TITLE
💡 - Options to skip downloading assets if cache already exist

### ISSUE THREAD

**Issue by alienxp03** [tespkg/actions-cache#27]
Would be good if we could get this option.

**Comment by jackieli-tes** [comment]
I'm not sure this is possible. How do you know the local assets are consistent with the remote?

**Comment by alienxp03** [comment]
One possible option is to check based on previous cache hit. Or any kind of cache key maybe? Some cache are very big and without this option, we have to pay quite a lot for S3 data transfer. And we could save few seconds/minutes too for each cache download.

From another repo: https://github.com/whywaita/actions-cache-s3#skipping-steps-based-on-cache-hit

**Comment by jackieli-tes** [comment]
Ah, yes, good point. We can check the previous downloaded file. I think I'll implement this one. Thanks for the suggestion.
