### ISSUE TITLE
Need a fresh release

### ISSUE THREAD

**Issue by tvthatsme** [tespkg/actions-cache#35]
The last release was November 2022, but there have been several improvements since then. I'd specifically like to be able to use [this output](https://github.com/tespkg/actions-cache/blob/main/src/utils.ts#L81). Can we get an updated release, please?

**Comment by tvthatsme** [comment]
I ended up publishing a fork of my own for now. If we can get an answer here, I'm happy to unlist my action. But for now I need these changes.

https://github.com/marketplace/actions/actions-cache-in-s3

**Comment by jackieli-tes** [comment]
Hi @tvthatsme , Thanks for follow this up. I published v1.4.0 for the feature you added. In addition, I upgrade most of the deps and published v1.5.0. 

Also, the v1 compatible tag is upgraded to latest tag

**Comment by tvthatsme** [comment]
Hi @jackieli-tes, thanks so much! This is perfect. Just delisted my forked action. Thanks for working on this!!
